name: cine_panda
description: "Veja onde assistir seus filmes favoritos."
publish_to: "none"
version: 1.0.0+1
environment:
  sdk: ^3.5.3
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.2.2
  provider: ^6.1.2
  flutter_dotenv: ^5.2.1
  flutter_launcher_icons: ^0.14.1
  google_nav_bar: ^5.0.6
  line_icons: ^2.0.3
  flutter_svg: ^2.0.10+1
  intl: ^0.19.0
  connectivity_plus: ^6.0.5
  skeletonizer: ^1.4.2
  sqflite: ^2.4.0
  path: ^1.9.0
  url_launcher: ^6.1.7
  lottie: ^3.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  sqflite_common_ffi: ^2.3.4

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/animations/
    - .env
